name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - media_uploader_widget/**
      - tests/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
